# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-30 15:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0002_auto_20180530_1003'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='lastchange_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
